# Generated by Django 2.2.2 on 2019-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajax',
            name='telephone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
